config/routes.rb
  map.connect "/payment_response" ,:controller=>"admin/payments",:action=>"create"
  map.connect "/admin/mail" ,:controller=>"admin/mail",:action=>"index"
  
  map.connect "/admin/delete_temprary_email" ,:controller=>"admin/mail",:action=>"delete_temprary_email"
  map.connect "/admin/delete_from_trash" ,:controller=>"admin/mail",:action=>"delete_from_trash"
  map.connect "/admin/flag_email" ,:controller=>"admin/mail",:action=>"flag_email"
  map.connect "/admin/show_flag_email" ,:controller=>"admin/mail",:action=>"show_flag_email"
  map.connect "/admin/compose_new_mail" ,:controller=>"admin/mail",:action=>"compose_new_mail"
  map.connect "/admin/create_sent_mail" ,:controller=>"admin/mail",:action=>"create_sent_mail"
  map.connect "/admin/create_sent_mail/:id" ,:controller=>"admin/mail",:action=>"create_sent_mail"
  
  
  
  map.connect "/admin/create_temporary_inbox" ,:controller=>"admin/mail",:action=>"create_temporary_inbox"
  map.connect "/admin/create_sent_mail_with_unknown" ,:controller=>"admin/mail",:action=>"create_sent_mail_with_unknown"  
  map.connect "/admin/show_message" ,:controller=>"admin/mail",:action=>"show_message"
  map.connect "/admin/replay_message" ,:controller=>"admin/mail",:action=>"replay_message"
  map.connect "/admin/replay_to_all" ,:controller=>"admin/mail",:action=>"replay_to_all"
  map.connect "/admin/delete_email",:controller=>"admin/mail",:action=>"delete_email"
  map.connect "/admin/delete_all_email",:controller=>"admin/mail",:action=>"delete_all_email"
  map.connect "/admin/create_label",:controller=>"admin/mail",:action=>"create_label"
  map.connect "/find_signature_label",:controller=>"admin/mail",:action=>"find_signature_label"
  map.connect "/find_signature",:controller=>"admin/mail",:action=>"find_signature"
  map.connect "/admin/flag_mail",:controller=>"admin/mail",:action=>"flag_mail"
  map.connect "/admin/delete_show_flag_mail",:controller=>"admin/mail",:action=>"delete_show_flag_mail"
  map.connect "/admin/delete_label",:controller=>"admin/mail",:action=>"delete_label"
  map.connect "/admin/unknown_email",:controller=>"admin/mail",:action=>"unknown_email"
  map.connect "/auto_complete_for_user_email",:controller=>"admin/mail",:action=>"auto_complete_for_user_email"
  map.connect "/admin/show_unknown_message",:controller=>"admin/mail",:action=>"show_unknown_message"
  map.connect "/admin/replay_message_to_unknown",:controller=>"admin/mail",:action=>"replay_message_to_unknown"
  

  
  map.connect "/admin/forward_email" ,:controller=>"admin/mail",:action=>"forward_email"
  map.connect "/admin/sent_mail" ,:controller=>"admin/mail",:action=>"sent_mail"
  map.connect "/admin/trash_mail" ,:controller=>"admin/mail",:action=>"trash_mail"
  map.connect "/admin/show_sent_message" ,:controller=>"admin/mail",:action=>"show_sent_message"
  map.connect "/admin/moveto" ,:controller=>"admin/mail",:action=>"moveto"
  map.connect "/admin/show_labeled_email" ,:controller=>"admin/mail",:action=>"show_labeled_email"
  map.connect "/admin/sent_flag_email" ,:controller=>"admin/mail",:action=>"sent_flag_email"
  map.connect "/admin/delete_sent_mail" ,:controller=>"admin/mail",:action=>"delete_sent_mail"
  map.connect "/admin/create_sent_mail_with_original_id/:id" ,:controller=>"admin/mail",:action=>"create_sent_mail_with_original_id"
  map.connect "/admin/profiles/compose_user_mail/:id",:controller=>"admin/profiles",:action=>"compose_user_mail"
  map.connect "/admin/profiles/create_sent_mail",:controller=>"admin/profiles",:action=>"create_sent_mail"
  map.connect "/admin/profiles/show_columns/:id",:controller=>"admin/profiles",:action=>"show_columns"
  map.connect "/show_message_sent/:id",:controller=>"admin/profiles",:action=>"show_message_sent"
  map.connect "/show_message_recd/:id",:controller=>"admin/profiles",:action=>"show_message_recd"
  
  
  
  map.resources :periods
  map.resources :people
  # Blank Specific Routes
  # Routes Related to SuperAdministrator
	map.namespace :superadmin do |sa|
		sa.connect '', :controller => 'superadmin/administration', :action => 'show'
		sa.resources :general_settings, :only => [:index, :update], :collection => { :editing => :get, :updating => :put }
		sa.resources :audits, :only => [:index]
		sa.resources :user_interfaces, :only => [:index, :update], :collection => { :editing => :get, :updating => :put, :check_color => :get, :colors_changing => :get }
		sa.resources :tasks, :only => [:index], :collection => { :run_task => :get }
		sa.resources :translations, :only => [:index, :update], :collection => { :updating => :put, :context_switching => :get, :translation_new => :any , :new_project => :any, :new_language => :any, :section_switching => :any }
      sa.resources :mailer_settings, :only => [:index], :collection => { :updating => :put }
		sa.resources :mailing_settings, :only => [:index], :collection => { :updating => :put }
		sa.resources :ecom_settings, :only => [:index], :collection => { :updating => :put }
    # Routes for Roles and Permissions in BA
    sa.resources :roles, :collection => {:validate => :post}
    sa.resources :permissions, :collection => {:validate => :post}
    sa.resources :google_analytics, :only => [:index], :collection => {:updating => :put}
	end
    map.connect "/admin/promoting_stuffs/update/:id",:controller=>"promoting_stuffs",:action=>"update"
    map.resources :promoting_stuffs  , :path_prefix => 'admin'
  
    map.resources :mailing_lists  , :path_prefix => 'admin'
    
    map.connect "/admin/show_studio_mail",:controller=>"mailing_lists",:action=>"show_studio_mail"
    
    map.connect "/admin/send_studio_email",:controller=>"mailing_lists",:action=>"send_studio_email"
    
    map.connect "/admin/send_mailing_email",:controller=>"mailing_lists",:action=>"send_mailing_email"
    
    map.connect "/admin/show_mailing_mail",:controller=>"mailing_lists",:action=>"show_mailing_mail"
  
      
  
    map.connect "/admin/booksshops/update/:id",:controller=>"booksshops",:action=>"update"
    
    map.resources :booksshops  , :path_prefix => 'admin'
    map.connect "/booksshops",:controller=>"booksshops",:action=>"index",:id=>"front"
    
    map.connect "/admin/app_homes/update/:id",:controller=>"app_homes",:action=>"update"
    map.resources :app_homes  , :path_prefix => 'admin'
    map.connect "/app_homes",:controller=>"app_homes",:action=>"index",:id=>"front"
    
    map.connect "/admin/front_end_pics/update/:id",:controller=>"front_end_pics",:action=>"update"
  
    map.connect "/admin/front_end_pics/select_pic/:id",:controller=>"front_end_pics",:action=>"select_pic"  
  
    
    map.resources :front_end_pics  , :path_prefix => 'admin'
    map.connect "/front_end_pics",:controller=>"front_end_pics",:action=>"index"
    
    map.connect "/admin/drawings/update/:id",:controller=>"drawings",:action=>"update"
    map.resources :drawings  , :path_prefix => 'admin'
    map.connect "/drawings",:controller=>"drawings",:action=>"index",:id=>"front"
    map.connect "/admin/links/approve/:id",:controller=>"links",:action=>"approve"
    map.connect "/admin/links/update/:id",:controller=>"links",:action=>"update"
    map.connect "/admin/signature",:controller=>"signatures",:action=>"index"
    map.connect "/add_frommail",:controller=>"signatures",:action=>"add_frommail"
    map.connect "/add_signature",:controller=>"signatures",:action=>"add_signature"

    
    
    map.resources :links  , :path_prefix => 'admin'
    map.resources :bottomline  , :path_prefix => 'admin'
    map.connect "/links",:controller=>"links",:action=>"index",:id=>"front"
    map.connect "/admin/competitions_users/update/:id",:controller=>"competitions_users",:action=>"update"
    map.connect "/admin/competitions_users/destroy/:id",:controller=>"competitions_users",:action=>"destroy"
    map.resources :competitions_users  , :path_prefix => 'admin'
    map.resources :competitions_artworks  , :path_prefix => 'admin'
    
  
  map.namespace :admin do |admin|
    admin.connect "/competitions/open/:id",:controller=>"competitions",:action=>"open"
    admin.connect "/competitions/finalist/:id",:controller=>"competitions",:action=>"finalist"
    admin.connect "/competitions/winner/:id",:controller=>"competitions",:action=>"winner"
    admin.connect "/competitions/send_winner_email/:id",:controller=>"competitions",:action=>"send_winner_email"
    admin.connect "/competitions/send_mail_to_artist/:id",:controller=>"competitions",:action=>"send_mail_to_artist"
    admin.connect "/competitions/send_winner_email/:id",:controller=>"competitions",:action=>"send_winner_email"
    
    admin.connect "/compcreate_sent_mail_to_artist/:id",:controller=>"competitions",:action=>"compcreate_sent_mail_to_artist"
    admin.connect "/competitions/auto_complete_for_profile_email",:controller=>"competitions",:action=>"auto_complete_for_profile_email"
    
    admin.connect "/compfind_signature_label",:controller=>"competitions",:action=>"compfind_signature_label"
    admin.connect "/compfind_signature",:controller=>"competitions",:action=>"compfind_signature"
    
    admin.connect "/profiles/exhibition_payment/:id",:controller=>"profiles",:action=>"exhibition_payment"
    admin.connect "/profiles/exhibition_payment_front/:id",:controller=>"profiles",:action=>"exhibition_payment_front"
    admin.connect "/profiles/edit_password/:id",:controller=>"profiles",:action=>"edit_password"
    admin.connect "/profiles/change_password/:id",:controller=>"profiles",:action=>"change_password"
    admin.connect "/send_news_letter",:controller=>"newsletters",:action=>"send_news_letter"
   
     
    
    # Generated by Restful Authentification
    admin.logout '/logout', :controller => 'sessions', :action => 'destroy'
    admin.login '/login', :controller => 'sessions', :action => 'new'
    admin.signup '/signup/:id', :controller => 'users', :action => 'new'
    admin.activate '/activate/:activation_code', :controller => 'users', :action => 'activate'

app/models/profile.rb
class Profile < ActiveRecord::Base

	belongs_to :user
	has_many :profiles_containers, :dependent => :delete_all
	# Relation N-1 getting Workspace objects through the 'users_workspaces' table
  CONTAINERS.each do |container|
    has_many container.pluralize.to_sym, :source => :container, :through => :users_profiles, :source_type => container.classify.to_s, :class_name => container.classify.to_s
  end
	
	has_many :profiles_categories
	has_many :categories, :through => :profiles_categories

	# Relation N-1 with the polymorphic 'contacts_workspaces' table
  has_many :contacts_workspaces, :as => :contactable, :dependent => :destroy

	#acts_as_searchable :full_text_fields => [:firstname, :lastname], :conditionnal_attribute => []
  validates_uniqueness_of :email_address,:message=>"Email Is Already Taken"
  validates_presence_of :first_name, :last_name,:message=>"Please Enter First Name And Last Name"
  validates_presence_of :suburb,:message=>"Please Enter Suburb"
  validates_presence_of :zip_code,:message=>"Please Enter Zip Code"
		
	# Validation of the format of these fields
  validates_format_of :first_name, :last_name, :with => /\A(#{ALPHA_AND_EXTENDED}|#{SPECIAL})+\Z/, :allow_blank => false,:message=>"Please Check The First Name"

  validates_format_of       :address, :with => /\A(#{ALPHA_AND_EXTENDED}|#{SPECIAL}|#{NUM})+\Z/, :allow_blank => false,:message=>"Please Check The Address"
	#validates_not_format_of   :address, :with => /(#{SCRIPTING_TAGS})/, :allow_blank => true
  validates_length_of       :phone_number, :in => 7..20, :allow_blank => false,:message=>"Please Enter Valid Phone Number"
  validates_format_of       :phone_number, :with => /(#{PHONE})/, :allow_blank => true
  validates_format_of			:website, :with => /(#{URL})/, :allow_blank => true,:message=>"Please Enter Valid Website"

	after_create :add_to_admin_contacts

	named_scope :superadmin_filtered, {
		:conditions => ["profiles.id > 0"]
	}

	named_scope :from_category, lambda{ |cat_id|
		{
			:select => "DISTINCT profiles.*",
			:joins => "LEFT JOIN profiles_categories ON profiles_categories.profile_id = profiles.id",
			:conditions => "profiles_categories.id = '#{cat_id}'"
		}
	}

	named_scope :with_conditions_on_user, lambda{ |*args|
		#raise args.inspect
		{ :select => "DISTINCT profiles.*", :joins => "LEFT JOIN users ON users.id = profiles.user_id" }.merge(args.first)
	}

	# Create Private worksapce for User on creation called 'Private space of user_login'
	def create_profile_workspace
		# Creation of the private workspace for the user
		ws = Workspace.new(:title => "Archive for #{self.full_name}",
      :description => "Archive for #{self.full_name}",
      :body => "Worksapce containing all the content linked to the contact #{self.full_name}",
      :creator_id => self.user_id,
      :available_items => get_configuration['sa_items'],
      :state => 'profile')
		# To assign the 'ws_admin' role to the user in his privte workspace
		ws.save(false)
		ws.profiles_containers.create(:profile_id => self.id)
	end

	def profile_workspace
		if c=ProfilesContainer.find(:first, :conditions => { :profile_id => self.id })
			return c.container
		else
			return nil
		end
	end

        def full_address_for_invoice
		 self.address.to_s + " " +self.country.to_s + " " +self.city.to_s
	end	
	def  full_name_for_invoice
	return self.first_name.to_s + " " + self.last_name.to_s 
	end
	def add_to_admin_contacts
		ws = User.find(:first, :conditions => { :system_role_id => Role.find_by_name('admin') }).private_workspace
		ContactsWorkspace.create(:workspace_id => ws.id, :contactable_id => self.id, :contactable_type => self.class.to_s)
		# 
		if self.user_id.nil?
			cat = Category.find(1) # TODO : how to be sure to always check the right one, need a :db_nae field or something
			ProfilesCategory.create(:profile_id => self.id, :category_id => cat.id)
		end
	end

	# User Full Name 'Lastname FirstName'
	def full_name(with_salutation=false)
		return (with_salutation && self.salutation ? self.salutation.to_s + " " : '')+ self.first_name.to_s + " " + self.last_name.to_s
  end

	def switch_workspace_to_user
		
	end
	
	def full_address(separator)
		res = [self.address, self.suburb, self.zip_code.to_s, self.city, self.state, self.country]
		return separator ? res.delete_if{ |e| e.nil? }.join(separator) : res
	end


#  [:address, :zip_code, :city, :country, :phone_number, :website, :biography].each do |m|
#		define_method m.to_s do
#			return self.specific_info ? self.specific_info[m] : nil
#		end
#	end
#
#	def specific_info= param
#		self.specific_info = param
#	end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/admin/profiles/_form.html.erb
<% blank_main_div(:title => 'Contact creation', :hsize => 'sixH') do %>

  <%= render :partial => 'admin/profiles/profile_fields', :locals => { :f => f } %>
  <%= blank_form_submit_button(:object => @current_object) %>

<% end %>

<div class="rightBlocks">
  <div class="itemShowRightBlock">
    <% if @current_object.new_record? %>
      <%= I18n.t('general.field.created_at')+' '+I18n.l(Time.now, :format => :verb) %>
    <% else %>
      <%= I18n.t('general.field.created_at')+' '+I18n.l(@current_object.created_at, :format => :verb) %><br />
      <%= I18n.t('general.field.updated_at')+' '+I18n.l(@current_object.updated_at, :format => :verb) %>
    <% end %>
  </div>

  <div class="itemShowRightBlock">
    <div class="blockCornerLeft"></div><div class="blockElementHeader twoH">Actions</div><div class="blockCornerRight"></div>
    <div class="blockElementBody">
      <%= link_to("Back to the list", admin_profiles_path) if @current_user.has_system_role('admin')   %>
      
      <%= link_to("Password", "/admin/profiles/edit_password/#{@current_object.user.id}") if @current_user.has_system_role('admin')   %>
      <% if !@current_object.new_record? %>
        <%= link_to "Show", admin_profile_path(@current_object) %>
  <%#= link_to I18n.t('general.object.comment').pluralize.capitalize, admin_comments_path %>
  <%#= link_to I18n.t('rating.index.link').pluralize, admin_ratings_path %>
  <%#= link_to I18n.t('general.notification.link'), admin_user_notifications_path(@current_object) %>
        <% if @current_object.user && @current_object.user.activation_code.to_s.size > 10 %>
          <%= link_to I18n.t('general.link.delete'), "javascript:;",
            :class => "deleteLink",
            :modal_id => "#modalDelete_#{@current_object.id.to_s}"
        %>
        
          <div style="display:none">
            <div id="modalDelete_<%=@current_object.id.to_s%>" class="modalDelete">
              <p>I18n.t('general.common_word.confirmation')</p>
              <%= link_to I18n.t('general.common_word.yes1'), admin_profile_path(@current_object.id), :method => :delete%> |
              <%= link_to I18n.t('general.common_word.no1'), "javascript:;", :class => "deleteClose" %>
            </div>
          </div>
        <% elsif @current_object.user %>
          <%= link_to (@current_object.user.activation_code=='locked' ? 'Unlock' : 'Lock'), locking_admin_user_path(@current_object.user_id) %>
        <% end %>
      <% end %>
    </div>
  </div>


  <div class="itemShowRightBlock">
    <div class="blockCornerLeft"></div><div class="blockElementHeader twoH">
      <%= 'Categories' %> <!-- TODO HINT -->
    </div><div class="blockCornerRight"></div>
    <div class="blockElementBody">
      <%= select_tag "profile[category_ids][]", options_from_collection_for_select(Category.all, 'id', 'name', :selected => @current_object.category_ids), :multiple => true, :size => 6 %>
    </div>
  </div>

</div>

app/views/admin/profiles/_profile_fields.html.erb
<%#*<label><%= I18n.t('people.field.salutation_label') %>
<%#*</label>%>
<%#*<div class="formElement">%>
  <%# %w(Mr Ms Miss).each do |s|  %>
    <%#= s %>
    <%#= radio_button_tag "#{(@current_object ? 'user['+f.object.class.to_s.downcase+'_attributes]' : f.object.class.to_s.downcase)}[salutation]", s, (f.object.salutation == s), :class => "checkboxes" %>
  <%# end %>
<%#*</div>%>

<%= f.text_field :first_name, :label => I18n.t('user.field.first_name_label')+" * : ", :hint => "Put your first name" %>

<%#= f.text_field :first_name, :label => I18n.t('user.field.middle_name_label')+" * : ", :hint => "Put your middle name" %>

<%= f.text_field :last_name, :label => I18n.t('user.field.last_name_label')+" * : ", :hint => "Put your last name" %>

<!--<label><%#= I18n.t('people.field.gender_label') %> : </label>
<div class="formElement">
  <%# %w(M F).each do |s|  %>
    <%#= s %>
    <%#= radio_button_tag "#{(@current_object ? 'user['+f.object.class.to_s.downcase+'_attributes]' : f.object.class.to_s.downcase)}[gender]", s, (f.object.gender == s), :class => "checkboxes" %>
  <%# end %>
</div>
-->
<%#= f.date_select :birth_date, { :start_year => 1900, :end_year => 2000, :include_blank => true }, :label => I18n.t('user.field.birth_date_label')+" * : ", :hint => "TODO hint" %>

<%#*<label><%= 'Categories' %>
<%#*</label>%>
<%#*<div class="formElement">%>
  <%# Category.all.each do |c| %>
    <%#= check_box_tag "#{(@current_object ? 'user['+f.object.class.to_s.downcase+'_attributes]' : f.object.class.to_s.downcase)}[category_ids][]", c.id, (f.object.categories.include?(c)), :class => "checkboxes" %>
    <%#= c.name %>
  <%# end %>
<%#*</div>%>


<!--<div class="formElement">
  <%#= f.text_field :nationality %>
</div>-->

<%#= check_box_tag "#{(@current_object ? 'user['+f.object.class.to_s.downcase+'_attributes]' : f.object.class.to_s.downcase)}[category_ids][]", c.id, (f.object.categories.include?(c)), :class => "checkboxes" %>
<%#= f.check_box :getting_newsletter, { :class => "checkboxes" } %>


<%# f.fields_for :specific_info do |si| %>
  <%= render :partial => 'admin/profiles/specific/artist_fields', :locals => { :f => f } %>
<%# end %>

app/views/admin/profiles/_profile_show.html.erb
  <%#* <b>Salutation:</b>  %>
  <%#=h profile.salutation %>

  <b>Full name </b>
  <%=h profile.full_name %><br />

  <b>Email </b>
  <%=h profile.email_address %><br />

	<b>Phone number </b> 
  <%=h profile.phone_number %><br />	

	<b> Website </b>
  <%= link_to profile.website, profile.website, :target => "_blank" %><br />


<!--  <b>Middle name:</b>
  <%#=h profile.middle_name %>

  <b>Last name:</b> 
  <%# =h profile.last_name %>

	  <b>Phone number :</b> 
  <%# =h profile.phone_number %><br />

 
  <b>Birth date:</b> 
  <%# =h profile.birth_date %><br />  

   <b>Gender:</b>	
  <%#= h profile.gender %><br /> 

  	<b>Nationality :</b>	
  <%#= h profile.nationality %><br />	

-->

app/views/admin/profiles/edit.html.erb
<% form_for @current_object, :url => admin_profile_path(@current_object.id), :builder => BlankFormBuilder do |f| %>

  <%= render :partial => 'form', :locals => { :f => f} %>

<% end %>

app/views/admin/profiles/index.html.erb
  
<% blank_main_div(:title =>"Contacts list (#{@num} results)", :hsize => 'sixH') do %>
  
  <table id="profiles">
    <thead>
        <tr>
          <th>First name</th>
          <th>Last name</th>
          <th>Email</th>
          <th>&nbsp  State</th>
          
        </tr>
    </thead>
    <tbody>
      <% @current_objects.each do |profile| %>
        <tr>
            <%if  profile.user.login != "admin" and  profile.user.login != "superadmin"%>
              <td><%=link_to profile.first_name , admin_profile_path(profile.id)%></td>
              <td><%=link_to profile.last_name , admin_profile_path(profile.id)%></td>
              <td><%=link_to profile.email_address, admin_profile_path(profile.id) %></td>
              <td><%=h profile.country_state %></td>
             <%else%>
              <td><%=link_to profile.first_name , '' %></td>
              <td><%=link_to profile.last_name , ''%></td>
              <td><%=link_to profile.email_address, '' %></td>
              <td><%=h profile.country_state %></td>
            <%end%>


  </tr>
 <% end %>
  </tbody>
  <tfoot>
    <tr style="display:none;">
      <td colspan="5">
	            No rows match the filter...
      </td>
    </tr>
  </tfoot>

</table>
              <br/></br>  
                        <div>
                          <form action="/admin/send_news_letter">
                            <%if @newsletter%>
                              <select size="6" name="newsletter"  id="category_ids_" >
                                <%for newsletter in @newsletter%>
                                <option  value="<%=newsletter.id%>"><%=newsletter.title%></option>
                                <%end%>
                              </select>
                            <%=hidden_field_tag "categoryid",@filters * ","%>
                            
                            <%=submit_tag "send newsletter", :style => "width:115px;"%>
                            <%end%>
                          </form>
                        </div>
            
<% end %>


<div class="rightBlocks">
	<div class="itemShowRightBlock">
	    <div class="blockCornerLeft"></div><div class="blockElementHeader twoH">
			Actions
		</div><div class="blockCornerRight"></div>
	    <div class="blockElementBody">
	        <%= link_to I18n.t('user.new.add_user'), new_admin_user_path %><br /><br />
			Filter the list with text <br />
			<input id="filter223" /><br /><br />
                        Filter the list by categories <br />
                        <div id="filterthecategory">
                        <%#= link_to 'All', admin_profiles_path %>
                        <%# Category.all.each do |cat| %>
                          <%#= link_to cat.name, admin_profiles_path(:category => cat.id) %>
                        <%# end %>
                        <% form_for 'filter', :url => filter_admin_profiles_path, :html => { :method =>:post } do |f| %>
                          <%= select_tag "category_ids[]", options_from_collection_for_select(Category.all, 'id', 'name', :selected => @filters), :multiple => true, :size => 6,:class=>"collectionlist" %>
                          <%= f.submit 'filter', :class => "submitfilter" %>
                        <% end %>
                        </div>
          
             </div>
                
                
	</div>
</div>



<script>
  $(document).ready(function()
    {
      $("#profiles").tablesorter();
        <%#*$("#profiles").tablesorter({ sortList: [[0, 0]], widgets: ['zebra'] });%>

        <%#*$("#profiles tbody tr").quicksearch({%>
            <%#*labelText: 'Search: ',%>
            <%#*attached: '#profiles',%>
            <%#*position: 'before',%>
            <%#*delay: 100,%>
            <%#*loaderText: 'Loading...',%>
            <%#*onAfter: function() {%>
                <%#*if ($("#profiles tbody tr:visible").length != 0) {%>
                    <%#*$("#profiles").trigger("update");%>
                    <%#*$("#profiles").trigger("appendCache");%>
                    <%#*$("#profiles tfoot tr").hide();%>
                <%#*}%>
                <%#*else {%>
                    <%#*$("#profiles tfoot tr").show();%>
                <%#*}%>
            <%#*}%>
        <%#*});%>

    }
);
</script>

app/views/admin/profiles/new.html.erb
<% form_for @current_object, :url => admin_profiles_path, :builder => BlankFormBuilder do |f| %>

  <%= render :partial => 'form', :locals => { :f => f} %>

<% end %>

app/views/admin/profiles/password.html.erb
<div id="container">
	<div class ="objectList small">
		<div class="blockCornerLeft"></div>
			<div class="blockElementHeader sixH">
						<span id="item_count">Change Password</span>
			</div>
			<div class="blockCornerRight"></div>
			<div class="contentList filtered sixH">
			    <table>
			    <form action="/admin/profiles/change_password/<%=params[:id]%>" method="post">
			      <tr><td>
              Password</td><td><%=password_field "user","password"%></td></tr><tr><td>
              Confirm Password</td><td><%=password_field "user","password_confirmation"%></td></tr>
                <tr><td><%=submit_tag%>
            </td></tr>
          </form>
          </table>
			</div>
		  </div>
	</div>
</div>